services:
  postgres:
    ports: !reset []
  redis:
    ports: !reset []
  api:
    ports: !reset []
    restart: always
  web:
    ports: !reset []
    restart: always
  bot:
    restart: always
  worker:
    restart: always
